### ISSUE TITLE
Hello.It still spawn slime on spigot 1.10.2

### ISSUE THREAD

**Issue by ThinkHO** [egold555/CorpseReborn#1]
I am using this plugin lastest version on the lastest version of spigot 1.10.2.But I found that it still spawn slime in the center of body.I really like this plugin.Can you fix it?:)

**Comment by egold555** [comment]
Hi. This is not a bug. This is so the corpse has a better hitbox. You can disable the slime hitbox in the config of you wish.

**Comment by ThinkHO** [comment]
The option 'new-hitboxes:' have set to true.If I have to set it to false?

**Comment by egold555** [comment]
If you don't want the slimes, set it to false.
