### ISSUE TITLE
Corpses Standing up when spawned

### ISSUE THREAD

**Issue by ZestyBlaze** [egold555/CorpseReborn#100]
Hi I'm playing in the 1.15 beta but everytime my corpses spawn in when I die, they are immediately standing up. The hitbox where I need to click for their head is always on the ground but the body stands up and its a little putting off because I'd like to use your plugin on my server and as a part of my Murder Mystery minigame.

**Comment by auriium** [comment]
I also have this issue as well

**Comment by egold555** [comment]
#89
