### ISSUE TITLE
Bugged Cow? Can be killed by the Wither, unlootable corpses

### ISSUE THREAD

**Issue by Zefferis** [egold555/CorpseReborn#21]
Is the bugged cow kill able? It seems that on occasion the corpse cannot be interacted with, I'm guessing its because the 'cow' that spawns to which you've got to interact has died?

The wither recently attacked some players corpses and left the bodies unlootable similar to other unlootable overworld corpses.

I assume thats because the cow died.

Thanks in advance (:

**Comment by egold555** [comment]
Hi. Could you send me your dump log (/cr dump). The cows should not be killable by players, never occured for me to test it with withers. I have a fix, just need to make sure I am understanding what the problem is

**Comment by Zefferis** [comment]
https://pastebin.com/Wr3NB0F8
