### ISSUE TITLE
Error Message On Death

### ISSUE THREAD

**Issue by remibarna** [egold555/CorpseReborn#24]
Hello,

I get kicked from my server with this message everytime I kill someone. 

https://gyazo.com/33179b28d31c12ff637ac39e6e50bf56?token=b71e18ac1d9951a2abee4ed8ab196d06

Very big issue please fix. (1.8.8 server)

**Comment by remibarna** [comment]
Found the issue. When you set the name tags to &4&l%corpse% it fucks it up. Please fix this as I would like to have color codes then regular player name tags (AnimatedNames)

**Comment by egold555** [comment]
Colored names do work, but minecraft is limited to 16 characters for a name tag. I have a way around this, just need to implement it correctly to bypass mojangs limitations.

**Comment by remibarna** [comment]
I see. 

Also I have AnimatedNames by max and there is a suffix under the main name tag. When I disable name tags users can see the suffix. What I mean by the suffix is like under the name tag on some servers it says "health" and etc. is there any way around that?

**Comment by egold555** [comment]
I am guessing you have a global health scoreboard that puts the health under everyone? Not sure if this will work but try sending a client side scoreboard for the health to the player? It might stop it rendering on the corpse. But the scoreboard rendering is client side and the corpses are client side 'players' so I am not really sure how to stop the client from rendering scoreboards. I will look into it though

**Comment by remibarna** [comment]
Yup I do. And kk thanks !
