### ISSUE TITLE
Issue with corpses. 

### ISSUE THREAD

**Issue by arturek1666** [egold555/CorpseReborn#4]
I decided as my title will be annoying corpses because there is big issue with them. I did already inform you about it but you say paperspigot is not supported and so on so i switched to spigot and quest what same issue with is:

Players can't pickup items I have to explain to each player to open the corpse on head it don't really work on body and players need to click 20 times or to open it that's one issue, Other issue is that after picking up items the corpse dispiriting but not the visible cow with means players can't place block. 

Full info:

spigot 1.11.2 February 26, 2017
Console: There is no error on the console :(
All my plugins:
AAC
AACAdditionPro_1.3.1
AsyncWorldEdit
AuthMe-5.2-spigot
citizens-2.0.21-SNAPSHOT
CoreProtect_2.14.2
CorpseReborn
CustomGUI
DeathLogPlus
EditableSign
Essentials
eZProtector
GlobalChestShop
HolographicDisplays
MobArena
Multiverse-Core-2.5
MyPreciousStone
orebfuscator-4.2.1
PermissionsEx-1.23.4
PluginManager
PreciousStones-1.11
ProtocolLib
PvPManager
RandomTeleport
sexymotd-1.4.3
SkinsRestorer-v12.9.7
StaffFacilities
Statistics
TreeAssist
Vault
WorldBorder
worldedit-bukkit-6.1.5
worldguard-6.2
WorldResetPlus
ChatControl

**Comment by egold555** [comment]
Please send me the link in chat when you do /corpsereborn dump

**Comment by arturek1666** [comment]
I can't do  that already removed your plugin and switched  to deferent.
