### ISSUE TITLE
CorpseClickEvent not getting fired.

### ISSUE THREAD

**Issue by midnjerry** [egold555/CorpseReborn#41]
I can capture CorpseRemoveEvent but not CorpseClickEvent.  I looked at your code, and I might be mistaken, but I don't see where CowHit calls the CorpseClickEvent.

**Comment by egold555** [comment]
The corpse click event is called in NMSBase. Make sure you have the new hitboxes enabled.
https://github.com/egold555/CorpseReborn/blob/master/src/org/golde/bukkit/corpsereborn/nms/NmsBase.java#L70

**Comment by midnjerry** [comment]
Thanks for the quick response.  I'll take a look.

**Comment by midnjerry** [comment]
I think I figured it out.  When set **looting-inventory:** to false in the config I can't detect the event.  When I set **looting-inventory: true** then I can click, open an inventory and detect the click.  

I don't want to open an inventory window, but I want to detect when it clicks.

**Comment by egold555** [comment]
Makes sense. I need to rework the plugin and the api a bit when I get a chance. 

Sent from my Android Phone

**Comment by midnjerry** [comment]
Okay so I was able to get around it by making my Listener a higher priority than CorpseReborn and then cancelling the event.  That way the inventory window never opens.  Unfortunately I can only detect right clicks, not left clicks :(

**Comment by egold555** [comment]
Yeah. Then that is a bug. I will refine the api when I update the plugin. Hopefully soon, just need to find time

**Comment by DracarysPro** [comment]
Any progress on this? It's still an issue

**Comment by egold555** [comment]
Been busy with finals in school. I have looked a bit into this but not enough to figure out what is going on. In therory I will have time to debug this this weekend.

**Comment by egold555** [comment]
Fixed in 2.13.2
