### ISSUE TITLE
Video evidence of issues

### ISSUE THREAD

**Issue by arturek1666** [egold555/CorpseReborn#5]
I did remove your plugin but I loved so much i decided to record the issues. As the console is really not showing any error.

MC version: 1.11.2

Video evidence:
https://youtu.be/GQtAbawmYww
This video is now available

**Comment by egold555** [comment]
Could you do these steps and I will see what I can do to reproduce the problem o my end.

1) Download latest version
2) do /corpsereborn dump 
3) send me the link it sends you in the chat

This should help me figure out what is causing your problem. I have a feeling it is a problem with other plugins canceling events but I will try to debug it as best as i can. Thanks for the video, this explains exactly whats wrong.

**Comment by arturek1666** [comment]
here you go: http://pastebin.com/1sbACLc5

**Comment by arturek1666** [comment]
By the way i checked without plugins and it's same issue :) xD

**Comment by egold555** [comment]
For the life of me I can not replicate this problem that you are having. I will keep trying to replicate it but I would try updating to the latest version of spigot and only put corpsereborn and see if the problem persists. Are you running a custom version of spigot or have any client side miss installed??

**Comment by arturek1666** [comment]
I download all my spigot from https://getbukkit.org/spigot and always the newest one

**Comment by egold555** [comment]
Fixed in latest version of CorpseReborn
