### ISSUE TITLE
[Bug] Head faces backwards if the player is OPd

### ISSUE THREAD

**Issue by Zefferis** [egold555/CorpseReborn#6]
Players who are OP'd and die with the plugin active have their corpses' head facing the ground,

Non-OP'd normal players have a normal corpse upon death.

(Our server doesn't use a permissions plugin so it's just default/OP players.

Plugin Version: 2.10.2
Java 8
Spigot 1.12 R0.1

**Comment by egold555** [comment]
Thanks for reporting this. I will test this but that is super strange. The head position is done by the person's pitch and yaw upon death. It might just be a coincidence that OP's heads are down in the ground but I will test this

**Comment by egold555** [comment]
Closed issue because I can not replicate and it seems like some other plugin may be causing this.
