### ISSUE TITLE
1.14 Support

### ISSUE THREAD

**Issue by MdsCool** [egold555/CorpseReborn#79]
Plugin is currently broken on 1.14.2, could this be updated?

**Comment by egold555** [comment]
I have been working on and off of porting it to 1.14.2. Mojang has changed a lot how beds work, and most of the ways I tricked the client into rendering a corpse are now broken.

**Comment by egold555** [comment]
I will try to get a update out today. For further updates, please check the Spigot Page: https://www.spigotmc.org/resources/corpsereborn.29875/
