### ISSUE TITLE
Players in spectator mode can see the CRHitbox nametag on the invisible cow

### ISSUE THREAD

**Issue by kNoAPP** [egold555/CorpseReborn#93]
When players look at the corpse in spectator mode, they can see the cow named "CRHitbox." This is a bit of debug I don't think the spectator should be able to see. I propose changing it to nothing or something configurable...

https://github.com/egold555/CorpseReborn/blob/f5146e3431251a219da59c6c13807d2707acf89e/CorpseReborn-Base/src/org/golde/bukkit/corpsereborn/nms/NmsBase.java#L102

ChatColor.WHITE + "" or something would be amazing.

**Comment by kNoAPP** [comment]
https://i.imgur.com/2MbbWZy.png

**Comment by egold555** [comment]
Hi! That is used to remove bugged cows, because I could not get custom NBT to save (not sure why).

I am a bit surprised people in spectator can see this because I set the visibility to invisible, and the cow is invisible.

Ill look into this though. What version of spigot are you running?
