### ISSUE TITLE
Copse standing on foot

### ISSUE THREAD

**Issue by MackleyMag** [egold555/CorpseReborn#95]
The corpse is standing on foot, not laying down like in bed

**Comment by MackleyMag** [comment]
Im in version 1.15.2  using the beta plugin, like in spigot

**Comment by egold555** [comment]
Hi! Thanks for reporting this issue. Does this occur right when you spawn the corpse? If not, how did you get this to occur?

**Comment by MackleyMag** [comment]
Hi, it happens randomly. Not always happening. When someone dies like up a 1x1 block or near a mountain’s border it occurs more

**Comment by egold555** [comment]
Closing. Whole discussion about this issue in #89
